### ISSUE TITLE
extracting the contents from nsdata 

### ISSUE THREAD

**Issue by sswain2** [mdejong/lzmaSDK#13]
Hello ,

I have a base64 string which I am converting to nsdata and that nsdata is in 7zip format , I want to decompress the data 

can you point me to correct direction

**Comment by mdejong** [comment]
So, in order to use the already existing LZMAExtractor class, you will need to un-base64 encode your data and then save it into a file in the tmp dir. Just write the NSData to a file in the tmp dir and then feed that filename path into the LZMAExtractor method as seen in the example app.
