### ISSUE TITLE
lzma decompression

### ISSUE THREAD

**Issue by sswain2** [mdejong/lzmaSDK#14]
hello ,

I am glad that you replied , I wanted to ask one question,

 I need to write my nsdata  to a file . the file should be a 7z or any text file is also possible .

this is the code I have used 

here I am writing my base64 decoded data in your filename.7z and after that I am using the LZMAExtractor to get its contents 
  
    NSString *tmpDirname = @"Extract7z";
    NSString *archiveFilename = @"yourfilename.7z";
    NSString *archiveResPath = [NSTemporaryDirectory()stringByAppendingPathComponent:archiveFilename];

    [decodedData writeToFile:archiveResPath atomically:YES];

    NSAssert(archiveResPath, @"can't find test.7z");
  
  NSArray *contents = [LZMAExtractor extract7zArchive:archiveResPath tmpDirName:tmpDirname];

while extracting it is getting crashed 

can you help me  please

**Comment by mdejong** [comment]
Make sure the data in the file is 7z data. Run in simulator and then NSLog(@"%@", archiveResPath) to see the output simulator path then copy the file to your own location and make sure it contains 7zip data. It must not be base64 or gzip encoded. Run with a command line 7za command to make sure you have a 7z archive.

**Comment by sswain2** [comment]
hello 

I have done as you said and I have created a file from the decoded data of my base64 string  .
I created a tmp file 

 I used the 7za command line and I am not able to unarchive the file 

it says the file cannot be opened as[ 7z] archive  
the file is open as lzma archive 

but I am able to unarchive using the unarchiver software in Mac 

am I doing some decoding mistakes from the base64 string , or can you tell me what is the solution for this . how to extract the contents of the lzma archive in iOS

**Comment by mdejong** [comment]
I don't know what you are doing wrong, but if you cannot open the file with the command line 7z then it is in the wrong format or it is still encoded in some way. You need to figure that part out for yourself before attempting to use a library to decode the 7zip archive.
