### ISSUE TITLE
Creating 7z archive

### ISSUE THREAD

**Issue by sashahilton00** [mdejong/lzmaSDK#7]
How difficult would it be to add 7z archival functionality to this sdk? I know it can extract, but as far as I can tell there is no functionality for writing. Is it possible to do?

**Comment by mdejong** [comment]
Anything is possible, but this functionality is outside the design scope of this specific software. The LZMA compression approach is highly asymmetric, meaning it takes a lot longer to compress than to decompress. There is value in decompressing on an iOS device, but the amount of CPU needed to compress is so much more that it is of little value on a low power and low memory device. You should feel free to take the original 7zip SDK and get the compiling and running under Obj-C if you wanted compression logic.
