### ISSUE TITLE
When I unzip the file，the app crash！

### ISSUE THREAD

**Issue by hlllmr1314** [mdejong/lzmaSDK#8]
When I unzip the 7z file，the app crash！The problem here
if (InFile_Open(&archiveStream.file, archivePath))
  {
    PrintError("can not open input file");
    return 1;
  }

2015-10-23 09:08:53.370 XHEnglishBrushStudent[14250:2712290] ---downloadUpdate>>>DownloaProgress,45 $$$ DownloaUnique,44 $$$ DownloadTitle,正在解压数据文件...
2015-10-23 09:08:53.378 XHEnglishBrushStudent[14250:2712290] Error: Error Domain=NSCocoaErrorDomain Code=4 "未能完成操作。（“Cocoa”错误 4。）" UserInfo=0x1742f2f00 {NSSourceFilePathErrorKey=/var/mobile/Containers/Data/Application/2D4AE180-C3B7-41C2-9F7A-566700DD876C/Documents/xuehai/2747/databases/ep.xh.yystwteach/book_exam44.100fen, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/2D4AE180-C3B7-41C2-9F7A-566700DD876C/Documents/xuehai/2747/databases/ep.xh.yystwteach/book_exam44.7z, NSFilePath=/var/mobile/Containers/Data/Application/2D4AE180-C3B7-41C2-9F7A-566700DD876C/Documents/xuehai/2747/databases/ep.xh.yystwteach/book_exam44.100fen, NSUnderlyingError=0x174442a90 "未能完成该操作。No such file or directory"}
2015-10-23 09:08:53.379 XHEnglishBrushStudent[14250:2712290] cd to /var/mobile/Containers/Data/Application/2D4AE180-C3B7-41C2-9F7A-566700DD876C/Documents/xuehai/2747/databases/ep.xh.yystwteach/tmp

/--------------------------------------------bt message-------------------------------------------------------------------/
* thread #31: tid = 0x2962e2, 0x000000010038e674 XHEnglishBrushStudent`do7z_extract_entry(archivePath=0x000000017018d5e0, archiveCachePath=0x0000000170342a20, entryName=0x0000000000000000, entryPath=0x0000000000000000, fullPaths=1) + 160 at 7zMain.c:558, queue = 'com.zhitongyun.IMMngrTaskQueue', stop reason = EXC_BREAKPOINT (code=1, subcode=0xe7ffdefe)
  * frame #0: 0x000000010038e674 XHEnglishBrushStudent`do7z_extract_entry(archivePath=0x000000017018d5e0, archiveCachePath=0x0000000170342a20, entryName=0x0000000000000000, entryPath=0x0000000000000000, fullPaths=1) + 160 at 7zMain.c:558
    frame #1: 0x0000000100390ae0 XHEnglishBrushStudent`+[LZMAExtractor extract7zArchive:dirName:preserveDir:](self=0x00000001007b1f48, _cmd=0x00000001006af0e2, archivePath=0x0000000144e8eaf0, dirName=0x0000000144e6f450, preserveDir=true) + 2880 at LZMAExtractor.m:138
    frame #2: 0x00000001004f7a88 XHEnglishBrushStudent`-[SevenZipHelper unZip:archiveDir:](self=0x0000000170018ff0, _cmd=0x00000001006ba491, file=0x0000000144e8eaf0, archiveDir=0x0000000144e6f450) + 124 at SevenZipHelper.m:31
    frame #3: 0x00000001004eeb38 XHEnglishBrushStudent`__45-[ExamDownloadManager execDBDataFileCompress]_block_invoke(.block_descriptor=<unavailable>) + 560 at ExamDownloadManager.m:445
    frame #4: 0x0000000100c30fd4 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #5: 0x0000000100c30f94 libdispatch.dylib`_dispatch_client_callout + 16
    frame #6: 0x0000000100c3bdb8 libdispatch.dylib`_dispatch_queue_drain + 780
    frame #7: 0x0000000100c342c4 libdispatch.dylib`_dispatch_queue_invoke + 132
    frame #8: 0x0000000100c3e5d4 libdispatch.dylib`_dispatch_root_queue_drain + 772
    frame #9: 0x0000000100c40248 libdispatch.dylib`_dispatch_worker_thread3 + 132
    frame #10: 0x0000000196f8d21c libsystem_pthread.dylib`_pthread_wqthread + 816
(lldb)

**Comment by mdejong** [comment]
It seems the archive path you are passing in does not exist. Is that ".../book_exam44.100fen" or should hat have a 7z extension on the filename. What exactly crashes? Does it assert or is something else going on?

**Comment by hlllmr1314** [comment]
I'm sorry, I found a problem with the code written！you can close this issue!
